/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
/*                                                      */
/* File:  ControlVelocityBrake.h                        */
/*                                                      */
/* Author: Automatically generated by Xfuzzy            */
/*                                                      */
/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

#ifndef XFUZZY
#define XFUZZY
/*------------------------------------------------------*/
/* Fuzzy Number                                         */
/*------------------------------------------------------*/

 typedef struct {
   double (* equal)(double x);
   double (* center)();
   double (* basis)();
   double (* param)(int i);
 } Consequent;

 typedef struct {
   double min;
   double max;
   double step;
   double (* imp)(double a, double b);
   double (* also)(double a, double b);
   int length;
   double* degree;
   int inputlength;
   double* input;
   Consequent* conc;
 } FuzzyNumber;

#endif /* XFUZZY */


#ifndef XFUZZY_ControlVelocityBrake
#define XFUZZY_ControlVelocityBrake
/*------------------------------------------------------*/
/* Inference Engine                                     */
/*------------------------------------------------------*/

#ifdef __cplusplus
extern "C"
{
#endif
void ControlVelocityBrakeInferenceEngine(double erroV, double dV, double* accelAjust, double* brakeAjust);
#ifdef __cplusplus
}
#endif
#endif /* XFUZZY_ControlVelocityBrake */
