#START VOXEL STUFF
map_type: voxel
origin_z: 0.0
#z_resolution: 0.15
#z_voxels: 16
#unknown_threshold: 9
#mark_threshold: 0
#END VOXEL STUFF

resolution: 0.1
origin_x: 0.0
origin_y: 0.0
width: 100
height: 100
  
#transform_tolerance: 0.3
#obstacle_range: 2.5
#max_obstacle_height: 2.0
#raytrace_range: 3.0

footprint: [[1.25, -0.8], [1.6, 0.0], [1.25, 0.8], [-1.2, 0.8], [-1.2, -0.8]]

robot_radius: 0.46
footprint_padding: 0.05
inflation_radius: 0.55
cost_scaling_factor: 10.0
lethal_cost_threshold: 100

#track_unknown_space: true
#publish_voxel_map: true

observation_sources: cloud 
cloud: 
  {
    sensor_frame: stereo_camera, 
    data_type: PointCloud2, 
    topic: /cloud_filtered, 
    marking: true, 
    clearing: true,
    max_obstacle_height: 2.5, 
    min_obstacle_height: 0.005,
    observation_persistence: 0.0,
    expected_update_rate: 1.0
  }
