local_costmap:
  #publish_voxel_map: true
  global_frame: /map
  #robot_base_frame: base_link
  robot_base_frame: base_footprint
  
  update_frequency: 1.0
  publish_frequency: 1.0
  
  #static_map: false
  #rolling_window: true
  
  #static_map: true
  #rolling_window: false
  
  #width: 2.0
  #height: 2.0
  
  #resolution: 0.1
  #origin_x: 0.0
  #origin_y: 0.0
