Header header
float64 x # position of the robot in x, relative to inertial frame
float64 y # position of the robot in y, relative to inertial frame
float64 z # position of the robot in z, relative to inertial frame
float64 x_dot # linear velocity in x
float64 y_dot # linear velocity in y
float64 z_dot # linear velocity in z
float64 roll_phi # euler angle - roll, orientation relative to inertial frame, in radians
float64 pitch_theta # euler angle - pitch, orientation relative to inertial frame, in radians
float64 yaw_psi # euler angle - yaw, orientation relative to inertial frame, in radians
float64 p_rate # body angular velocity around roll
float64 q_rate # body angular velocity around pitch
float64 r_rate # body angular velocity around yaw
float64 steerAngle # in radians
