<?xml version="1.0"?>
<!--
*  Copyright (C) 2012, Laboratorio de Robotica Movel - ICMC/USP
 *  Rafael Luiz Klaser <rlklaser@gmail.com>
 *  http://lrm.icmc.usp.br
 *
 *  Apoio FAPESP: 2012/04555-4
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file bbx.urdf.xacro
 * @brief 
 * @author Rafael Luiz Klaser <rlklaser@gmail.com>
 * @date Mai 24, 2013
 *
 */
-->
<robot
	xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:xacro="http://ros.org/wiki/xacro"
>
	<include filename="$(find lrm_description)/urdf/inertia_tensors.urdf.xacro" />
	<include filename="$(find lrm_description)/urdf/clubcar/templates.urdf.xacro" />


	<link name="bbx_base_front_left_link">
		<xacro:inertial_minimal />
	</link>
	<link name="bbx_base_front_right_link">
		<xacro:inertial_minimal />
	</link>
	<link name="bbx_base_rear_left_link">
		<xacro:inertial_minimal />
	</link>
	<link name="bbx_base_rear_right_link">
		<xacro:inertial_minimal />
	</link>



	<link name="bbx_top_front_left_link">
		<xacro:inertial_minimal />
	</link>
	<link name="bbx_top_front_right_link">
		<xacro:inertial_minimal />
	</link>
	<link name="bbx_top_rear_left_link">
		<xacro:inertial_minimal />
	</link>
	<link name="bbx_top_rear_right_link">
		<xacro:inertial_minimal />
	</link>


	<joint
		name="joint_base_link_to_bbx_base_front_left_link"
		type="fixed"
	>
		<origin
			rpy="0 0 0"
			xyz="1.5 0.8 -${base_height}" />
		<parent link="base_link" />
		<child link="bbx_base_front_left_link" />
	</joint>

	<joint
		name="joint_base_link_to_bbx_base_front_right_link"
		type="fixed"
	>
		<origin
			rpy="0 0 0"
			xyz="1.5 -0.8 -${base_height}" />
		<parent link="base_link" />
		<child link="bbx_base_front_right_link" />
	</joint>

	<joint
		name="joint_base_bbx_base_rear_left_link"
		type="fixed"
	>
		<origin
			rpy="0 0 0"
			xyz="-1.5 0.8 -${base_height}" />
		<parent link="base_link" />
		<child link="bbx_base_rear_left_link" />
	</joint>

	<joint
		name="joint_base_bbx_base_rear_right_link"
		type="fixed"
	>
		<origin
			rpy="0 0 0"
			xyz="-1.5 -0.8 -${base_height}" />
		<parent link="base_link" />
		<child link="bbx_base_rear_right_link" />
	</joint>



	<joint
		name="joint_base_link_to_bbx_top_front_left_link"
		type="fixed"
	>
		<origin
			rpy="0 0 0"
			xyz="1.5 0.8 ${car_height - base_height}" />
		<parent link="base_link" />
		<child link="bbx_top_front_left_link" />
	</joint>

	<joint
		name="joint_base_link_to_bbx_top_front_right_link"
		type="fixed"
	>
		<origin
			rpy="0 0 0"
			xyz="1.5 -0.8 ${car_height - base_height}" />
		<parent link="base_link" />
		<child link="bbx_top_front_right_link" />
	</joint>

	<joint
		name="joint_base_link_top_rear_left_link"
		type="fixed"
	>
		<origin
			rpy="0 0 0"
			xyz="-1.5 0.8 ${car_height - base_height}" />
		<parent link="base_link" />
		<child link="bbx_top_rear_left_link" />
	</joint>

	<joint
		name="joint_base_link_top_rear_right_link"
		type="fixed"
	>
		<origin
			rpy="0 0 0"
			xyz="-1.5 -0.8 ${car_height - base_height}" />
		<parent link="base_link" />
		<child link="bbx_top_rear_right_link" />
	</joint>
	
</robot>