<?xml version="1.0"?>
<!--
*  Copyright (C) 2012, Laboratorio de Robotica Movel - ICMC/USP
 *  Rafael Luiz Klaser <rlklaser@gmail.com>
 *  http://lrm.icmc.usp.br
 *
 *  Apoio FAPESP: 2012/04555-4
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file bars.urdf.xacro
 * @brief 
 * @author Rafael Luiz Klaser <rlklaser@gmail.com>
 * @date Dez 12, 2012
 *
 */
-->
<robot
	xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:xacro="http://ros.org/wiki/xacro"
>
<!-- 
	<include filename="$(find lrm_description)/urdf/clubcar/bar.urdf.xacro" />
 -->
	<include filename="$(find lrm_description)/urdf/clubcar/bar.susp.urdf.xacro" />
	<include filename="$(find lrm_description)/urdf/clubcar/bar.gazebo.xacro" />

	<xacro:bar
		suspension="${front_suspension}"
		position="front"
		side="left"
		size="${front_axle/2}"
		type="revolute"
	>
		<origin
			xyz="${-wheel_diameter/4} 0 0"
			rpy="0 0 ${25*M_PI/180}" />
		<geometry>
			<box size="${wheel_diameter/2 +0.02} 0.02 0.02" />
		</geometry>
	</xacro:bar>

	<xacro:bar_transmission
		position="front"
		side="left" />
 
	<xacro:bar
	    suspension="${front_suspension}"
		position="front"
		side="right"
		size="${-front_axle/2}"
		type="revolute"
	>
		<origin
			xyz="${-wheel_diameter/4} 0 0"
			rpy="0 0 ${-25*M_PI/180}" />
		<geometry>
			<box size="${wheel_diameter/2 +0.02} 0.02 0.02" />
		</geometry>
	</xacro:bar>
	<xacro:bar_transmission
		position="front"
		side="right" />

	<xacro:bar
	    suspension="${rear_suspension}"
		position="rear"
		side="left"
		size="${rear_axle/2}"
		type="fixed"
	>
		<origin
			xyz="0 0 0"
			rpy="0 0 0" />
		<geometry>
			<cylinder
				radius="0.03"
				length="0.045" />
		</geometry>
	</xacro:bar>

	<xacro:bar
	    suspension="${rear_suspension}"
		position="rear"
		side="right"
		size="${-rear_axle/2}"
		type="fixed"
	>
		<origin
			xyz="0 0 0"
			rpy="0 0 0" />
		<geometry>
			<cylinder
				radius="0.03"
				length="0.045" />
		</geometry>
	</xacro:bar>

</robot>