<?xml version="1.0"?>
<!--
*  Copyright (C) 2012, Laboratorio de Robotica Movel - ICMC/USP
 *  Rafael Luiz Klaser <rlklaser@gmail.com>
 *  http://lrm.icmc.usp.br
 *
 *  Apoio FAPESP: 2012/04555-4
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file wheel.urdf.xacro
 * @brief 
 * @author Rafael Luiz Klaser <rlklaser@gmail.com>
 * @date Dez 12, 2012
 *
 */
-->
<robot
	xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:xacro="http://ros.org/wiki/xacro"
>
	<include filename="$(find lrm_description)/urdf/clubcar/wheel.gazebo.xacro" />
	<include filename="$(find lrm_description)/urdf/inertia_tensors.urdf.xacro" />
	<include filename="$(find lrm_description)/urdf/clubcar/templates.urdf.xacro" />

	<xacro:macro
		name="car_wheel"
		params="position side rotation size"
	>
		<xacro:wheel_gazebo
			position="${position}"
			side="${side}" />

		<link name="${position}_${side}_wheel">
			<xacro:inertial_sphere
				mass="${wheel_mass}"
				diameter="${wheel_diameter}" />
			<visual>
				<origin
					xyz="0 0 0"
					rpy="0 0 ${rotation}" />
				<geometry>
					<mesh
						filename="package://lrm_description/meshes/wheel.dae"
						scale="0.63 0.88 0.63" />
				</geometry>
				<material name="Roda">
					<color rgba="1.0 1.0 0.0 1.0" />
				</material>
			</visual>
			
			<collision>
				<origin
					xyz="0 0 0"
					rpy="${M_PI/2} 0 0" />
				<geometry>
					<cylinder
						radius="${wheel_diameter/2}"
						length="${wheel_width}" />
				</geometry>
				<!-- SDF:Gaazebo
				<surface>
					<bounce>
						<restitution_coefficient>0.0002</restitution_coefficient>
						<threshold>0.0001</threshold>
					</bounce>
					<friction>
						<ode>
							<mu>1.0</mu>
							<mu2>1.0</mu2>
						</ode>
					</friction>
					<contact>
						<ode>
							<kp>100000.0</kp>
							<kd>1.0</kd>
						</ode>
					</contact>
				</surface>
				-->
			</collision>
			
		</link>

		<joint
			name="joint_${position}_${side}_wheel"
			type="continuous"
		>
			<parent link="${position}_${side}_bar_link" />
			<child link="${position}_${side}_wheel" />
			<origin
				xyz="0.0 ${size} 0"
				rpy="0 0 0" />
			<axis
				xyz="0 1 0"
				rpy="0 0 0" />
			<joint_properties
				damping="0.0"
				friction="0.0" />
			<anchor xyz="0 0 0" />
		</joint>

	</xacro:macro>
</robot>