string[] model_names                                      # name of the model
lrm_gazebo/ModelJointsState[] model_joints_states # model pose and joint positions
---
bool success                                              # return true if spawn successful
string status_message                                     # comments if available
