## #START VOXEL STUFF
## map_type: voxel
## origin_z: 0.0
## #z_resolution: 0.15
## #z_voxels: 16
## #unknown_threshold: 9
## #mark_threshold: 0
## #END VOXEL STUFF

## resolution: 0.1
## origin_x: 0.0
## origin_y: 0.0
## width: 100
##height: 100
  
#transform_tolerance: 0.3
#obstacle_range: 2.5
#max_obstacle_height: 2.0
#raytrace_range: 3.0

footprint: [[1.25, -0.8], [1.6, 0.0], [1.25, 0.8], [-1.6, 0.8], [-1.6, -0.8]]

## robot_radius: 0.46
## footprint_padding: 0.05
## inflation_radius: 1.0
## cost_scaling_factor: 10.0
## lethal_cost_threshold: 100

#track_unknown_space: true
#publish_voxel_map: true


map_type: costmap
transform_tolerance: 0.4
obstacle_range: 5 #p/ ré 0.5
raytrace_range: 10.0 #p/ ré 1
inflation_radius: 0.2
robot_radius: 0.8
max_obstacle_height: 1.0
footprint_padding: 0.001
cost_scaling_factor: 10
lethal_cost_threshold: 100


observation_sources: cloud 
cloud: 
  {
    sensor_frame: stereo_camera, 
    data_type: PointCloud2, 
    #topic: /stereo/points_stat, 
    topic: /cloud/points_local_scan, 
    marking: true, 
    clearing: true,
    max_obstacle_height: 1.0, 
    min_obstacle_height: 0.1,
    observation_persistence: 0.01,
    expected_update_rate: 2.0
  }
