#Independent settings for the planner's costmap
global_costmap: 
  #global_frame: /global_map
  global_frame: map
  #robot_base_frame: base_link
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 5.0
  
  static_map: true
  rolling_window: false
  
  #static_map: true
  #rolling_window: false
  
  resolution: 0.1
  #origin_x: 0.0
  #origin_y: 0.0
  
#  recovery_behaviors:
#    - name: 'conservative_reset'
#      type: 'clear_costmap_recovery/ClearCostmapRecovery'
#    - name: 'aggressive_reset'
#      type: 'clear_costmap_recovery/ClearCostmapRecovery'
