#footprint_padding: 0.05
#controller_frequency: 1.0
#controller_patience: 100
#base_global_planner: SBPLLatticePlanner


base_global_planner: SBPLLatticePlanner
planner_patience: 50.0
clearing_rotation_allowed: false
controller_frequency: 10.0

# Recovery
recovery_behaviors:  [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]