<?xml version="1.0"?>
<!--
*  Copyright (C) 2012, Laboratorio de Robotica Movel - ICMC/USP
 *  Rafael Luiz Klaser <rlklaser@gmail.com>
 *  http://lrm.icmc.usp.br
 *
 *  Apoio FAPESP: 2012/04555-4
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file base.urdf.xacro
 * @brief 
 * @author Rafael Luiz Klaser <rlklaser@gmail.com>
 * @date Dez 12, 2012
 *
 */
-->
<robot>

	<link name="base_footprint" />
	<link name="base_link">
		<inertial>
			<mass value="${car_weight}" />
			<origin xyz="0 0 0" />
			<inertia
				ixx="0.1"
				ixy="0.0"
				ixz="0.0"
				iyy="0.1"
				iyz="0.0"
				izz="0.1" />
		</inertial>
	</link>
	<link name="rear_axle_link">
		<inertial>
			<mass value="${inertia_null_mass}" />
			<origin xyz="${inertia_null_x} ${inertia_null_y} ${inertia_null_z}" />
			<inertia
				ixx="${inertia_null_ixx}"
				ixy="${inertia_null_ixy}"
				ixz="${inertia_null_ixz}"
				iyy="${inertia_null_iyy}"
				iyz="${inertia_null_iyz}"
				izz="${inertia_null_izz}" />
		</inertial>
	</link>
	<link name="front_axle_link">
		<inertial>
			<mass value="${inertia_null_mass}" />
			<origin xyz="${inertia_null_x} ${inertia_null_y} ${inertia_null_z}" />
			<inertia
				ixx="${inertia_null_ixx}"
				ixy="${inertia_null_ixy}"
				ixz="${inertia_null_ixz}"
				iyy="${inertia_null_iyy}"
				iyz="${inertia_null_iyz}"
				izz="${inertia_null_izz}" />
		</inertial>
	</link>

	<link name="base_odometry">
		<inertial>
			<mass value="${inertia_null_mass}" />
			<origin xyz="${inertia_null_x} ${inertia_null_y} ${inertia_null_z}" />
			<inertia
				ixx="${inertia_null_ixx}"
				ixy="${inertia_null_ixy}"
				ixz="${inertia_null_ixz}"
				iyy="${inertia_null_iyy}"
				iyz="${inertia_null_iyz}"
				izz="${inertia_null_izz}" />
		</inertial>
	</link>

	<link name="chassis_link">
		<inertial>
			<mass value="${inertia_null_mass}" />
			<origin xyz="${inertia_null_x} ${inertia_null_y} ${inertia_null_z}" />
			<inertia
				ixx="${inertia_null_ixx}"
				ixy="${inertia_null_ixy}"
				ixz="${inertia_null_ixz}"
				iyy="${inertia_null_iyy}"
				iyz="${inertia_null_iyz}"
				izz="${inertia_null_izz}" />
		</inertial>
		<visual>
			<origin
				xyz="0 0 0.04"
				rpy="0 0 0" />
			<geometry>
				<mesh
					filename="package://lrm_description/meshes/carina_texture.dae"
					scale="0.85 0.9 0.85" />
			</geometry>
			<material name="Car">
				<color rgba="0.0 1.0 0.0 1.0" />
			</material>
		</visual>
		<collision>
			<origin
				xyz="-0.12 0.0 0.0"
				rpy="0 0 0" />
			<geometry>
				<box size="2.8 1.2 1.5" />
			</geometry>
		</collision>
	</link>

	<link name="imu_link">
		<inertial>
			<mass value="0.05" />
			<origin
				rpy="0 0 0"
				xyz="0 0 0" />
			<inertia
				ixx="0.0001"
				ixy="0"
				ixz="0"
				iyy="0.000001"
				iyz="0"
				izz="0.0001" />
		</inertial>
		<visual>
			<origin
				rpy="0 0 0"
				xyz="0 0 0" />
			<geometry>
				<box size="0.045 0.03 0.015" />
			</geometry>
			<material name="Orange">
				<color rgba="1 0.5 0.0 1.0" />
			</material>
		</visual>
		<collision>
			<origin
				rpy="0 0 0"
				xyz="0 0 0" />
			<geometry>
				<box size="0.02 0.04 0.02" />
			</geometry>
		</collision>
	</link>

	<joint
		name="imu_joint"
		type="fixed"
	>
		<axis xyz="1 0 0" />
		<origin xyz="${-rear_to_base} 0 0.225" />
		<parent link="base_link" />
		<child link="imu_link" />
	</joint>
	
	<joint
		name="chassis_joint"
		type="fixed"
	>
		<origin
			xyz="0.15 0 0.28"
			rpy="0 0 0" />
		<parent link="base_link" />
		<child link="chassis_link" />
	</joint>

	<joint
		name="base_footprint_joint"
		type="fixed"
	>
		<origin
			rpy="0 0 0"
			xyz="0 0 ${base_height}" />
		<parent link="base_footprint" />
		<child link="base_link" />
	</joint>

	<joint
		name="base_link_to_rear_axle_joint"
		type="fixed"
	>
		<origin
			rpy="0 0 0"
			xyz="${-rear_to_base} 0 ${-base_height + wheel_diameter/2}" />
		<parent link="base_link" />
		<child link="rear_axle_link" />
	</joint>

	<joint
		name="base_link_to_front_axle_joint"
		type="fixed"
	>
		<origin
			rpy="0 0 0"
			xyz="${front_to_base} 0.0 ${-base_height + wheel_diameter/2}" />
		<parent link="base_link" />
		<child link="front_axle_link" />
	</joint>

	<joint
		name="base_odometry_joint"
		type="fixed"
	>
		<origin
			rpy="0 0 0"
			xyz="0.0 0.0 ${-wheel_diameter/2}" />
		<parent link="rear_axle_link" />
		<child link="base_odometry" />
	</joint>

</robot>
